module.exports = {
    DAY:86399500,
    CODE:{
        VERIFY_INVALID:{
            STATUSCODE:101,
            MSG:'验证码失效'
        },
        VERIFY_ERROR:{
            STATUSCODE:102,
            MSG:'验证码错误'
        },
        LOGIN_TOKEN_INVALID:{
            STATUSCODE:103,
            MSG:'登录超时'
        },
        LOGIN_NO_LOGIN:{
            STATUSCODE:104,
            MSG:'未登录'
        },
        USERNAME_REPTER:{
            STATUSCODE:105,
            MSG:'用户名重复'
        },
        USERNAME_INVALID:{
            STATUSCODE:106,
            MSG:'账号格式不符合要求'
        },
        WORD_NOT_FIND:{
            STATUSCODE:107,
            MSG:'未查询到：'
        }
    }
}
